"""Add database connection status tracking

Revision ID: bb2a0f9d33d3
Revises: 39caf25b9217
Create Date: 2026-01-11 15:44:06.148630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb2a0f9d33d3'
down_revision = '39caf25b9217'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the ENUM type first
    connectionstatus_enum = sa.Enum('online', 'offline', 'syncing', 'unknown', name='connectionstatus')
    connectionstatus_enum.create(op.get_bind(), checkfirst=True)
    
    # Add columns with server default for non-nullable column
    op.add_column('databases', sa.Column('connection_status', connectionstatus_enum, nullable=False, server_default='unknown'))
    op.add_column('databases', sa.Column('connection_error', sa.Text(), nullable=True))
    op.add_column('databases', sa.Column('last_checked_at', sa.DateTime(), nullable=True))
    
    # Drop the server default after adding the column
    op.alter_column('databases', 'connection_status', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('databases', 'last_checked_at')
    op.drop_column('databases', 'connection_error')
    op.drop_column('databases', 'connection_status')
    
    # Drop the ENUM type
    sa.Enum(name='connectionstatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
