"""Add last_collection_at to databases

Revision ID: f9a81690970e
Revises: 621d6d22f245
Create Date: 2026-01-10 13:04:58.837490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9a81690970e'
down_revision = '621d6d22f245'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('databases', sa.Column('last_collection_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('databases', 'last_collection_at')
    # ### end Alembic commands ###
