"""add_stripe_and_onboarding_fields

Revision ID: 39caf25b9217
Revises: f9a81690970e
Create Date: 2026-01-10 13:27:40.327649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39caf25b9217'
down_revision = 'f9a81690970e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('onboarding_completed', sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET onboarding_completed = false")
    op.alter_column('users', 'onboarding_completed', nullable=False)
    op.create_index(op.f('ix_users_stripe_customer_id'), 'users', ['stripe_customer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_stripe_customer_id'), table_name='users')
    op.drop_column('users', 'onboarding_completed')
    op.drop_column('users', 'stripe_customer_id')
    # ### end Alembic commands ###
